---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-alerting-rules
  annotations:
    reloader.stakater.com/match: "true"
data:
  loki-alerting-rules.yaml: |-
    groups:
      - name: loki-alerts
        rules:
           - alert: HighErrorRate
             expr: |
               sum(rate({app="loki"} |= "error" [5m])) by (job) > 3
             for: 5m
             labels:
               severity: critical
             annotations:
               summary: High error rate in Loki logs
               description: "Loki logging more than 3 error messages in 5 minutes."