name: Install/Upgrade 

on:
  repository_dispatch:
    types: [install_unoplat_loki_stack]
  workflow_dispatch: 

jobs:
  install_civo:
    runs-on: ubuntu-latest

    steps:

    - uses: azure/setup-kubectl@v3
      id: install    


    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.11.1


    - uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Print payload
      env:
        MESSAGE: ${{ github.event.client_payload.message }}
      run: echo $MESSAGE


    - name: Install jq
      run: sudo apt-get install jq

    - name: Add Helm repo
      run: helm repo add unoplat-observability-loki-stack https://unoplat.github.io/unoplat-observability-loki-stack

    - name: Update Helm repo
      run: helm repo update

    - name: Install latest pre-release version
      run: |
        version=$(helm search repo unoplat-observability-loki-stack/signoz --versions --devel --output json | jq -r '.[0].version')
        helm upgrade --install unoplat-observability-loki-stack --namespace unoplat-observability unoplat-observability-loki-stack/loki-stack --version $version --devel --create-namespace 
