name: Update Loki-Stack 

on:
  schedule:
    - cron: '0 9 * * 1' # Run daily at 00:00 UTC
  workflow_dispatch: # Allows manual triggering of the workflow
#write description for all below
jobs:
  update-values:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout our repository
      uses: actions/checkout@v2
      with:
        ref: upstream-sync

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.11.1

    - name: Add Loki Helm repository
      run: |
        helm repo add grafana https://grafana.github.io/helm-charts

        helm repo update

    - name: Fetch Signoz Helm chart
      run: |
        helm fetch --untar grafana/loki-stack

    - name: Move loki-stack Helm Charts to charts folder
      run: |
        rsync -av loki-stack/ charts/loki-stack/

    - name: Keep it for debug
      run: |
        git status     

    - name: Get Rid of Unnecessary Files
      run: |
        rm -rf loki-stack        
    - name: Keep it for debug
      run: |
        git status     

    - name: Install yq
      run: |
        sudo snap install yq

    - name: Login to Github Container Registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - uses: kubescape/github-action@main
      continue-on-error: true
      with:
        format: sarif
        outputFile: helm_results
        files: "charts/loki-stack"

    - name: Keep it for debug
      run: |
        git status 

    - name: Upload Kubescape scan results to Github Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: helm_results.sarif  
        category: "Kubescape scan for Helm Charts"

    - name: Moving scan results to appropriate folders
      run: |
        echo "Moving helm_results.sarif to reports/kubernetes-nsa-cisa-yaml-scan-analysis/helm_results_${TIMESTAMP}.sarif"
        mv -f "helm_results.sarif" "reports/kubernetes-nsa-cisa-yaml-scan-analysis/helm_results_${TIMESTAMP}.sarif"

    - name: Push changes to our repository
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add charts/*
        git add reports/*
        git commit -m "added charts and scan results"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: upstream-sync

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: 'Sync with Upstream'
        commit-message: 'Changes Detected'
        branch: 'upstream-sync'
        base: 'develop'
        token: ${{ secrets.GITHUB_TOKEN }}  